### ISSUE TITLE
the mod crash my server can use ur mode it a great mod 

### ISSUE THREAD

**Issue by kyubiSSJ1** [Kotori316/FlexibleMarker#2]
the version is 1.12.2

**Comment by Kotori316** [comment]
Give me the crash log, please.

**Comment by kyubiSSJ1** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SplashAnimationCoremod (SplashAnimation-0.2.1.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  CorePlugin (SmoothFont-mc1.12.2-2.1.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  LoadingPlugin (Xaeros_Minimap_20.7.1_Forge_1.12.jar)
  RandomPatches (randompatches-1.12.2-1.17.2.1.jar)
  ApotheosisCore (Apotheosis-1.12.2-1.12.5.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 4/13/20 3:13 AM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/tileentity/TileEntitySpecialRenderer
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.tileentity.TileEntitySpecialRenderer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 33 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@3e850122 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 35 more
Caused by: java.lang.RuntimeException: Attempted to load class bwy for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 37 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.19.0-0.bpo.6-amd64
	Java Version: 1.8.0_242, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 1710759768 bytes (1631 MB) / 2224029696 bytes (2121 MB) up to 4772593664 bytes (4551 MB)
	JVM Flags: 2 total; -Xmx5120M -Xms512M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 149 mods loaded, 149 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                        | Version                  | Source                                               | Signature                                |
	|:----- |:------------------------- |:------------------------ |:---------------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft                 | 1.12.2                   | minecraft.jar                                        | None                                     |
	| LC    | mcp                       | 9.42                     | minecraft.jar                                        | None                                     |
	| LC    | FML                       | 8.0.99.99                | forge-1.12.2-14.23.5.2847.jar                        | None                                     |
	| LC    | forge                     | 14.23.5.2847             | forge-1.12.2-14.23.5.2847.jar                        | None                                     |
	| LC    | smoothfontcore            | mc1.12.2-2.1             | minecraft.jar                                        | None                                     |
	| LC    | xaerominimap_core         | 1.12.2-1.0               | minecraft.jar                                        | None                                     |
	| LC    | foamfixcore               | 7.7.4                    | minecraft.jar                                        | None                                     |
	| LC    | opencomputers|core        | 1.7.5.192                | minecraft.jar                                        | None                                     |
	| LC    | randompatches             | 1.12.2-1.17.2.1          | randompatches-1.12.2-1.17.2.1.jar                    | None                                     |
	| LC    | quarryplus                | 12.3.6                   | AdditionalEnchantedMiner-1.12.2-12.3.6-universal.jar | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 |
	| LC    | quarryplus_ct             | 12.3.6                   | AdditionalEnchantedMiner-1.12.2-12.3.6-universal.jar | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 |
	| LC    | ic2                       | 2.8.170-ex112            | industrialcraft-2-2.8.170-ex112.jar                  | de041f9f6187debbc77034a344134053277aa3b0 |
	| LC    | advanced_machines         | 61.0.1                   | Advanced Machines-61.0.1.jar                         | None                                     |
	| LC    | advanced_solar_panels     | 4.3.0                    | Advanced Solar Panels-4.3.0.jar                      | None                                     |
	| LC    | advancementbook           | 1.0.3                    | Advancement_Book-1.12-1.0.3.jar                      | None                                     |
	| LC    | appliedenergistics2       | rv6-stable-7             | appliedenergistics2-rv6-stable-7.jar                 | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LC    | bdlib                     | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2.jar                         | None                                     |
	| LC    | ae2stuff                  | 0.7.0.4                  | ae2stuff-0.7.0.4-mc1.12.2.jar                        | None                                     |
	| LC    | animalcrops               | 1.12.2-0.2.0             | AnimalCrops-1.12.2-0.2.0.jar                         | None                                     |
	| LC    | placebo                   | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                             | None                                     |
	| LC    | apotheosis                | 1.12.4                   | Apotheosis-1.12.2-1.12.5.jar                         | None                                     |
	| LC    | applecore                 | 3.2.0                    | AppleCore-mc1.12.2-3.2.0.jar                         | None                                     |
	| LC    | charset                   | 0.5.6.4                  | Charset-Lib-0.5.6.4.jar                              | None                                     |
	| LC    | crafttweaker              | 4.1.20                   | CraftTweaker2-1.12-4.1.20.563.jar                    | None                                     |
	| LC    | mtlib                     | 3.0.6                    | MTLib-3.0.6.jar                                      | None                                     |
	| LC    | modtweaker                | 4.0.17                   | modtweaker-4.0.17.jar                                | None                                     |
	| LC    | jei                       | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                            | None                                     |
	| LC    | appleskin                 | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                           | None                                     |
	| LC    | aroma1997core             | 2.0.0.2                  | Aroma1997Core-1.12.2-2.0.0.2.jar                     | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LC    | aroma1997sdimension       | 2.0.0.2                  | Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.jar      | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LC    | morphtool                 | 1.2-21                   | Morph-o-Tool-1.2-21.jar                              | None                                     |
	| LC    | autoreglib                | 1.3-32                   | AutoRegLib-1.3-32.jar                                | None                                     |
	| LC    | baubles                   | 1.5.2                    | Baubles-1.12-1.5.2.jar                               | None                                     |
	| LC    | bibliocraft               | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                    | None                                     |
	| LC    | blockcraftery             | 1.12.2-1.3.1             | blockcraftery-1.12.2-1.3.1.jar                       | None                                     |
	| LC    | bookshelf                 | 2.3.590                  | Bookshelf-1.12.2-2.3.590.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | buildcraftlib             | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                         | None                                     |
	| LC    | buildcraftcore            | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                         | None                                     |
	| LC    | buildcraftbuilders        | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                         | None                                     |
	| LC    | buildcrafttransport       | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                         | None                                     |
	| LC    | buildcraftsilicon         | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                         | None                                     |
	| LC    | buildcraftenergy          | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                         | None                                     |
	| LC    | reborncore                | 3.14.1.457               | RebornCore-1.12.2-3.14.1.457-universal.jar           | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LC    | techreborn                | 2.23.1.1003              | TechReborn-1.12.2-2.23.1.1003-universal.jar          | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LC    | forestry                  | 5.8.2.387                | forestry_1.12.2-5.8.2.387.jar                        | None                                     |
	| LC    | theoneprobe               | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                          | None                                     |
	| LC    | buildcraftcompat          | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                         | None                                     |
	| LC    | buildcraftfactory         | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                         | None                                     |
	| LC    | buildcraftrobotics        | 7.99.24.6                | buildcraft-all-7.99.24.6.jar                         | None                                     |
	| LC    | cctweaked                 | 1.86.2                   | cc-tweaked-1.12.2-1.86.2.jar                         | None                                     |
	| LC    | computercraft             | 1.86.2                   | cc-tweaked-1.12.2-1.86.2.jar                         | None                                     |
	| LC    | chisel                    | MC1.12.2-1.0.2.45        | Chisel-MC1.12.2-1.0.2.45.jar                         | None                                     |
	| LC    | chiselsandbits            | 14.33                    | chiselsandbits-14.33.jar                             | None                                     |
	| LC    | codechickenlib            | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux              | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar              | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | cofhcore                  | 4.6.6                    | CoFHCore-1.12.2-4.6.6.1-universal.jar                | None                                     |
	| LC    | cofhworld                 | 1.4.0                    | CoFHWorld-1.12.2-1.4.0.1-universal.jar               | None                                     |
	| LC    | compactsolars             | 1.12.2-5.0.18.341        | CompactSolars-1.12.2-5.0.18.341-universal.jar        | None                                     |
	| LC    | craftingtweaks            | 8.1.9                    | CraftingTweaks_1.12.2-8.1.9.jar                      | None                                     |
	| LC    | crafttweakerjei           | 2.0.3                    | CraftTweaker2-1.12-4.1.20.563.jar                    | None                                     |
	| LC    | dragonmounts              | 1.12.2-1.6.3             | DragonMounts2-1.12.2-1.6.3.jar                       | None                                     |
	| LC    | eplus                     | 5.0.176                  | EnchantingPlus-1.12.2-5.0.176.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | enderstorage              | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar          | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | energyconverters          | 1.3.6.24                 | energyconverters_1.12.2-1.3.6.24.jar                 | None                                     |
	| LC    | ffs                       | 1.12.2-2.2.5             | Fancy Fluid Storage-1.12.2-2.2.5.jar                 | None                                     |
	| LC    | fastbench                 | 1.7.2                    | FastWorkbench-1.12.2-1.7.2.jar                       | None                                     |
	| LC    | flatcoloredblocks         | mc1.12-6.8               | flatcoloredblocks-mc1.12-6.8.jar                     | None                                     |
	| LC    | foamfix                   | 0.10.5-1.12.2            | foamfix-0.10.5-1.12.2.jar                            | None                                     |
	| LC    | forgelin                  | 1.8.4                    | Forgelin-1.8.4.jar                                   | None                                     |
	| LC    | forgemultipartcbe         | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | microblockcbe             | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar         | None                                     |
	| LC    | minecraftmultipartcbe     | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar         | None                                     |
	| LC    | ftbbackups                | 1.1.0.1                  | FTBBackups-1.1.0.1.jar                               | None                                     |
	| LC    | ftblib                    | 5.4.7.0                  | FTBLib-5.4.7.0.jar                                   | None                                     |
	| LC    | ftbutilities              | 5.4.0.124                | FTBUtilities-5.4.0.124.jar                           | None                                     |
	| LC    | gravisuite                | 3.1.1                    | Gravitation Suite-3.1.1.jar                          | None                                     |
	| LC    | ichunutil                 | 7.2.1                    | iChunUtil-1.12.2-7.2.1.jar                           | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | gravitygun                | 7.0.0                    | GravityGun-1.12.2-7.0.1.jar                          | None                                     |
	| LC    | modularrouters            | 1.12.2-3.2.2             | modular-routers-1.12.2-3.2.2.jar                     | None                                     |
	| LC    | guideapi                  | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                          | None                                     |
	| LC    | harvest                   | 1.12-1.2.7-20            | Harvest-1.12-1.2.7-20.jar                            | None                                     |
	| LC    | thaumcraft                | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                     | None                                     |
	| LC    | railcraft                 | 12.0.0                   | railcraft-12.0.0.jar                                 | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LC    | thermalfoundation         | 2.6.7                    | ThermalFoundation-1.12.2-2.6.7.1-universal.jar       | None                                     |
	| LC    | twilightforest            | 3.8.689                  | twilightforest-1.12.2-3.8.689-universal.jar          | None                                     |
	| LC    | immersiveengineering      | 0.12-89                  | ImmersiveEngineering-0.12-89.jar                     | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LC    | immersivecables           | 1.3.2                    | ImmersiveCables-1.12.2-1.3.2.jar                     | None                                     |
	| LC    | teslacorelib              | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | industrialforegoing       | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.12.13-237.jar           | None                                     |
	| LC    | thermalexpansion          | 5.5.7                    | ThermalExpansion-1.12.2-5.5.7.1-universal.jar        | None                                     |
	| LC    | simplecorn                | 2.5.10                   | SimpleCorn1.12-1.12-2.5.10.jar                       | None                                     |
	| LC    | integrationforegoing      | 1.12.2-1.9               | IntegrationForegoing-1.12.2-1.9.jar                  | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| LC    | inventorytweaks           | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                             | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LC    | ironchest                 | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.71.846.jar                      | None                                     |
	| LC    | jeibees                   | 0.9.0.5                  | jeibees-0.9.0.5-mc1.12.2.jar                         | None                                     |
	| LC    | journeymap                | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                          | None                                     |
	| LC    | jee                       | 1.0.7                    | JustEnoughEnergistics-1.12.2-1.0.7.jar               | None                                     |
	| LC    | longfallboots             | 1.2.1a                   | longfallboots-1.2.1b.jar                             | None                                     |
	| LC    | magicbees                 | 1.0                      | MagicBees-1.12.2-3.1.10.jar                          | None                                     |
	| L     | flexiblemarker            | 1.6                      | Marker-1.6-universal.jar                             | None                                     |
	| L     | mcmultipart               | 2.5.3                    | MCMultiPart-2.5.3.jar                                | None                                     |
	| L     | modularforcefieldsystem   | 3.0.1                    | MFFS-1.12.2-4.0.1.0_1.12_cc3a5aa.jar                 | None                                     |
	| L     | minetogether              | unspecified              | minetogether-1.10.2-2.1.3.jar                        | None                                     |
	| L     | minetogetherserver        | unspecified              | minetogether-1.10.2-2.1.3.jar                        | None                                     |
	| L     | numina                    | 1.12.2-1.0.38            | Numina-1.12.2-1.0.38.jar                             | None                                     |
	| L     | powersuits                | 1.12.2-1.0.46            | ModularPowersuits-1.12.2-1.0.46.jar                  | None                                     |
	| L     | morpheus                  | 1.12.2-3.5.106           | Morpheus-1.12.2-3.5.106.jar                          | None                                     |
	| L     | mrtjpcore                 | 2.1.4.43                 | MrTJPCore-1.12.2-2.1.4.43-universal.jar              | None                                     |
	| L     | netherendingores          | 1.12.2-1.3               | Netherending-Ores-1.12.2-1.3.jar                     | None                                     |
	| L     | opencomputers             | 1.7.5.192                | OpenComputers-MC1.12.2-1.7.5.192.jar                 | None                                     |
	| L     | theframework              | 1.12.2-1.0.1-build-T23   | TheFramework-1.12.2-1.0.1-build-T23.jar              | None                                     |
	| L     | peripheralsplusone        | 1.12.2-1.1-build-T58     | PeripheralsPlusOne-1.12.2-1.1-build-T58.jar          | None                                     |
	| L     | playerplates              | 1.12.2-1.3.1.1           | playerplates-1.12.2-1.3.1.1.jar                      | None                                     |
	| L     | plethora-core             | 1.2.2                    | plethora-1.12.2-1.2.2.jar                            | None                                     |
	| L     | plethora                  | 1.2.2                    | plethora-1.12.2-1.2.2.jar                            | None                                     |
	| L     | portalgun                 | 7.1.0                    | PortalGun-1.12.2-7.1.0.jar                           | None                                     |
	| L     | projectred-core           | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-Base.jar                 | None                                     |
	| L     | projectred-compat         | 1.0                      | ProjectRed-1.12.2-4.9.4.120-compat.jar               | None                                     |
	| L     | projectred-integration    | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-integration.jar          | None                                     |
	| L     | projectred-transmission   | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-integration.jar          | None                                     |
	| L     | projectred-fabrication    | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-fabrication.jar          | None                                     |
	| L     | projectred-illumination   | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-lighting.jar             | None                                     |
	| L     | projectred-expansion      | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-mechanical.jar           | None                                     |
	| L     | projectred-relocation     | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-mechanical.jar           | None                                     |
	| L     | projectred-transportation | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-mechanical.jar           | None                                     |
	| L     | projectred-exploration    | 4.9.4.120                | ProjectRed-1.12.2-4.9.4.120-world.jar                | None                                     |
	| L     | projectx                  | 2.2.7                    | ProjectX-1.12.2-2.2.7-universal.jar                  | None                                     |
	| L     | xreliquary                | 1.12.2-1.3.4.786         | Reliquary-1.12.2-1.3.4.786.jar                       | None                                     |
	| L     | retroexchange             | 1.0.0                    | Retro-Exchange-1.12.2-1.0.7.jar                      | None                                     |
	| L     | silverfish                | 0.0.19                   | Silverfish-1.12.2-0.0.19-universal.jar               | None                                     |
	| L     | soulshardsrespawn         | 1.12.2-1.1.1-13          | SoulShardsRespawn-1.12.2-1.1.1-13.jar                | None                                     |
	| L     | stevescarts               | 2.4.31.135               | StevesCarts-1.12.2-2.4.31.135.jar                    | None                                     |
	| L     | thaumicenergistics        | 2.2.2                    | thaumicenergistics-2.2.2.jar                         | None                                     |
	| L     | tcinventoryscan           | 2.0.10                   | ThaumicInventoryScanning_1.12.2-2.0.10.jar           | None                                     |
	| L     | thaumictinkerer           | 1.12.2-5.0-353c71c       | thaumictinkerer-1.12.2-5.0-353c71c.jar               | None                                     |
	| L     | thermaldynamics           | 2.5.6                    | ThermalDynamics-1.12.2-2.5.6.1-universal.jar         | None                                     |
	| L     | thermalinnovation         | 0.3.6                    | ThermalInnovation-1.12.2-0.3.6.1-universal.jar       | None                                     |
	| L     | topaddons                 | 1.12.2-1.11.0            | topaddons-1.12.2-1.11.0.jar                          | None                                     |
	| L     | torchmaster               | 1.7.1.74                 | torchmaster_1.12.2-1.7.1.74.jar                      | None                                     |
	| L     | traverse                  | 1.6.0                    | Traverse-1.12.2-1.6.0-69.jar                         | None                                     |
	| L     | wanionlib                 | 1.12.2-2.2               | WanionLib-1.12.2-2.2.jar                             | None                                     |
	| L     | worldcontrol              | 1.0.31                   | WorldControl-1.0.31.jar                              | None                                     |
	| L     | worldedit                 | 6.1.10-SNAPSHOT          | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar    | None                                     |
	| L     | wrcbe                     | 2.3.1                    | WR-CBE-1.12.2-2.3.1.30-universal.jar                 | None                                     |
	| L     | yabba                     | 1.1.2.53                 | YABBA-1.1.2.53.jar                                   | None                                     |
	| L     | techreborn_compat         | 1.0.0                    | TechReborn-ModCompatibility-1.12.2-1.1.0.49.jar      | None                                     |
	| L     | mysticallib               | 1.12.2-1.3.1             | mysticallib-1.12.2-1.3.1.jar                         | None                                     |
	| L     | teslacorelib_registries   | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                     | None                                     |
	| L     | unidict                   | 1.12.2-2.9.2             | UniDict-1.12.2-2.9.2.jar                             | None                                     |

	Loaded coremods (and transformers): 
SplashAnimationCoremod (SplashAnimation-0.2.1.jar)
  pl.asie.splashanimation.core.SplashProgressTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  li.cil.oc.common.asm.ClassTransformer
CorePlugin (SmoothFont-mc1.12.2-2.1.jar)
  bre.smoothfont.asm.Transformer
AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
ForgelinPlugin (Forgelin-1.8.4.jar)
  
LoadingPlugin (Xaeros_Minimap_20.7.1_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
RandomPatches (randompatches-1.12.2-1.17.2.1.jar)
  com.therandomlabs.randompatches.core.RPTransformer
ApotheosisCore (Apotheosis-1.12.2-1.12.5.jar)
  shadows.ApotheosisTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Kotori316** [comment]
Uploaded v1.8
https://www.curseforge.com/minecraft/mc-mods/flexiblemarker/files/2929415
I started dedicated server and server didn't crash with v1.8

**Comment by kyubiSSJ1** [comment]
ty it work
